version: '3.1'

services:
  postgres:
    build:
      context: './dockerfiles/postgres'
    restart: 'unless-stopped'
    env_file:
      - './secrets/postgres.env'
      - './secrets/prosody-db.env'
      - './secrets/seafile-db.env'
      - './secrets/synapse-db.env'
    volumes:
      - './data/postgres/:/var/lib/postgresql/data:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.10'

  postgres-upgrade:
    build:
      context: './dockerfiles/postgres-upgrade'
    env_file:
      - './secrets/postgres.env'
      - './secrets/prosody-db.env'
      - './secrets/seafile-db.env'
      - './secrets/synapse-db.env'
    volumes:
      - './data/postgres/:/var/lib/postgresql/data:Z'

  memcached:
    build:
      context: './dockerfiles/memcached'
    restart: 'unless-stopped'
    networks:
      backend:
        ipv4_address: '10.0.0.11'

  prosody:
    build:
      context: './dockerfiles/prosody'
    restart: 'unless-stopped'
    depends_on:
      - 'postgres'
    env_file:
      - './secrets/prosody-db.env'
    volumes:
      - './logs/prosody:/var/log/prosody:Z'
      - './data/prosody:/etc/prosody:Z,ro'
    networks:
      backend:
        ipv4_address: '10.0.0.12'

  znc:
    build:
      context: './dockerfiles/znc'
    restart: 'unless-stopped'
    volumes:
      - './data/znc:/znc-data:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.13'

  seafile:
    build:
      context: './dockerfiles/seafile'
    env_file:
      - './env/seafile.env'
      - './secrets/seafile-db.env'
      - './secrets/seafile-su.env'
    environment:
      - 'SEAFILE_POSTGRES_HOST=postgres'
      - 'SEAFILE_MEMCACHED_HOST=memcached:11211'
    restart: 'unless-stopped'
    depends_on:
      - 'postgres'
      - 'memcached'
    volumes:
      - './logs/seafile:/seafile/logs:Z'
      - './data/seafile:/seafile/data:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.14'

  synapse:
    build:
      context: './dockerfiles/synapse'
      args:
        SYNAPSE_HOST: 'bnounu.com'
    env_file:
      - './secrets/synapse-db.env'
      - './secrets/synapse-pepper.env'
    environment:
      - 'SYNAPSE_POSTGRES_HOST=postgres'
    restart: 'unless-stopped'
    depends_on:
      - 'postgres'
      - 'matrix-irc'
    volumes:
      - './data/synapse:/data:Z'
      - './data/synapse-app-services:/app-services:Z'
      - './data/synapse-uploads:/uploads:Z'
      - './data/synapse-media-store:/media_store:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.15'

  matrix-irc:
    build:
      context: './dockerfiles/matrix-irc'
    env_file:
      - './env/matrix-irc.env'
    restart: 'unless-stopped'
    volumes:
      - './data/matrix-irc:/data:Z'
      - './data/synapse-app-services:/app-services:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.16'

  weechat:
    build:
      context: './dockerfiles/weechat'
    restart: 'unless-stopped'
    volumes:
      - './data/weechat:/weechat-data:Z'
    networks:
      backend:
        ipv4_address: '10.0.0.17'

  nginx:
    build:
      context: './dockerfiles/nginx'
    restart: 'unless-stopped'
    env_file:
      - './env/nginx.env'
      - './env/seafile.env'
    volumes:
      - './logs/nginx:/var/log/nginx:Z'
      - './data/nginx.conf.template:/etc/nginx/nginx.conf.template:Z,ro'
      - './data/nginx-certs:/etc/certs:Z,ro'
    networks:
      backend:
        ipv4_address: '10.0.0.5'
    expose:
      - '5222'
      - '5281'
      - '31415'
      - '31416'
      - '31417'
      - '8000'
      - '8448'
    ports:
      - '31416:31416'
      - '31417:31417'
      - '8000:8000'
      - '8448:8448'

networks:
  backend:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '10.0.0.0/24'
