#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER synapse WITH PASSWORD '$SYNAPSE_DB_PASSWORD';
    CREATE DATABASE synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0;
    GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;
EOSQL
